---
language: python
python:
  - "2.7"
  - "3.7"
services:
  - docker
install:
  - pip install molecule docker
script:
  - molecule --version
  - ansible --version
  - cd roles/docker
  - molecule test
