docker_edition: 'ce'
docker_package: docker-{{ docker_edition }}
docker_package_state: latest

docker_install_compose: true
docker_compose_version: "1.22.0"
docker_compose_path: /usr/local/bin/docker-compose

docker_yum_repo_url: https://download.docker.com/linux/centos/docker-{{ docker_edition }}.repo
docker_yum_repo_enable_edge: 0
docker_yum_repo_enable_test: 0

docker_users:
  - docker
  - root



pkgs:
- device-mapper-persistent-data
- yum-utils
- lvm2