---
- name: enable docker remote API at port 2376
  become: yes
  lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: '^ExecStart=\/usr\/bin\/dockerd -H fd:\/\/'
    line: 'ExecStart=/usr/bin/dockerd {{ enable_docker_api }} -H fd://'
  register: file_has_been_changed

- name: restart docker deamon
  become: yes
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  when: file_has_been_changed|bool