---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: upgrade all packages
  become: yes
  yum:
    name: "{{pkgs}}"
    state: present


##not working for a bug ? (https://github.com/ansible/ansible/issues/11814)
- name: Add Docker repository
  become_method: sudo
  yum_repository:
    name: docker-ce.repo
    description: Docker repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0
