---
- name: Ensure old versions of Docker are not installed.
  yum:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: upgrade all packages
  become: yes
  become_method: sudo
  yum:
    name: "{{pkgs}}"
    state: present

- name: Add Docker repository
  become: yes
  #shell: "sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  #ignore_errors: yes
  yum_repository:
    name: docker-ce.repo
    description: Docker repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker.
  yum:
    name: "{{docker_pkgs}}"
    state: present
  #notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0
