---
- name: Ensure old versions of Docker are not installed.
  yum:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: upgrade required packages
  become: yes
  yum:
    name: "{{ pkgs }}"
    state: present

- name: check if Docker repository is present
  become: yes
  stat:
    path: /etc/yum.repos.d/{{ docker_package }}.repo
  register: stat_result

- name: Add Docker repository, if it doesnt exist already
  become: yes
  command: "yum-config-manager --add-repo {{ docker_yum_repo_url }}"
  when: not stat_result.stat.exists|bool

- name: Install Docker
  become: yes
  yum:
    name: "{{ docker_pkgs }}"
    state: present

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers


- include_tasks: docker-users.yml
  when: docker_users | length > 0
